# https://taskfile.dev
version: '3'

tasks:
  pretty:
    - perltidy -b scripts/t/*.t scripts/lib/*.pm scripts/*.pl
  test:
    - prove -Iscripts/lib scripts/t
  epub:
    sources: 
      - scripts/t/*.t
      - 'bm.md'
      - 'changes.md'
      - 'contributors.md'
      - 'mx.md'
      - 'nz.md'
      - 'notes/airport-bathrooms.md'
      - 'notes/tsa.md'
      - 'uk.md'
      - 'us/*.md'
      - ./scripts/gen-epub.pl
    generates: 
      - ./output/trans-travel.epub
    cmds:
      - perl ./scripts/gen-epub.pl
      # did we do good?
      - { task: test}

  pdf:
    sources: 
      - 'bm.md',
      - 'changes.md',
      - 'contributors.md',
      - 'mx.md'
      - 'nz.md'
      - 'notes/airport-bathrooms.md'
      - 'notes/tsa.md'
      - 'uk.md'
      - 'us/*.md'
      - ./scripts/gen-pdf.pl
    generates: 
      - ./output/trans-travel.pdf
    cmds:
      - perl ./scripts/gen-pdf.pl > output/trans-travel.html
      - weasyprint output/trans-travel.html output/trans-travel.pdf
    
  docsify:
    cmds:
      - perl scripts/gen-docsify-sidebar.pl > _sidebar.md
